project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true
files:
  - source: common/src/commonMain/resources/MR/base/strings.xml
    translation: common/src/commonMain/resources/MR/%locale%/strings.xml
    ignore:
      - common/src/commonMain/resources/MR/images/
      - common/src/commonMain/resources/MR/files/
  - source: common/src/commonMain/resources/MR/base/plurals.xml
    translation: common/src/commonMain/resources/MR/%locale%/plurals.xml
    ignore:
      - common/src/commonMain/resources/MR/images/
      - common/src/commonMain/resources/MR/files/
