[versions]
kotlin = "1.8.0"
kotlin-serialization = "1.5.0-RC"
agp = "7.4.0"
compose = "1.4.0-alpha05"
compose-compiler = "1.4.0"
compose-material3 = "1.1.0-alpha05"
accompanist = "0.29.1-alpha"
ktor = "2.2.3"
koin = "3.2.0"

[libraries]
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.0"
androidx-activity = "androidx.activity:activity-compose:1.6.1"
androidx-paging = "androidx.paging:paging-compose:1.0.0-alpha17"

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version = "1.0.0-alpha01" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material3" }
compose-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }

coil-compose = "io.coil-kt:coil-compose:2.2.2"

navigation = "dev.olshevski.navigation:reimagined:1.3.1"

media3-exoplayer = "androidx.media3:media3-exoplayer:1.0.0-beta03"

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlin-serialization" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"

brotli = "org.brotli:dec:0.1.2"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }